class AddKeys < ActiveRecord::Migration
  def change
    add_foreign_key "attempts", "workout_scores", name: "attempts_active_score_id_fk", column: "active_score_id"
    add_foreign_key "attempts", "exercise_versions", name: "attempts_exercise_version_id_fk"
    add_foreign_key "attempts_tag_user_scores", "attempts", name: "attempts_tag_user_scores_attempt_id_fk"
    add_foreign_key "attempts_tag_user_scores", "tag_user_scores", name: "attempts_tag_user_scores_tag_user_score_id_fk"
    add_foreign_key "attempts", "users", name: "attempts_user_id_fk"
    add_foreign_key "attempts", "workout_scores", name: "attempts_workout_score_id_fk"
    add_foreign_key "choices_multiple_choice_prompt_answers", "choices", name: "choices_multiple_choice_prompt_answers_choice_id_fk"
    add_foreign_key "choices_multiple_choice_prompt_answers", "multiple_choice_prompt_answers", name: "choices_MC_prompt_answers_MC_prompt_answer_id_fk"
    add_foreign_key "choices", "multiple_choice_prompts", name: "choices_multiple_choice_prompt_id_fk"
    add_foreign_key "course_enrollments", "course_offerings", name: "course_enrollments_course_offering_id_fk"
    add_foreign_key "course_enrollments", "course_roles", name: "course_enrollments_course_role_id_fk"
    add_foreign_key "course_enrollments", "users", name: "course_enrollments_user_id_fk"
    add_foreign_key "course_exercises", "courses", name: "course_exercises_course_id_fk"
    add_foreign_key "course_exercises", "exercises", name: "course_exercises_exercise_id_fk"
    add_foreign_key "course_offerings", "courses", name: "course_offerings_course_id_fk"
    add_foreign_key "course_offerings", "terms", name: "course_offerings_term_id_fk"
    add_foreign_key "courses", "organizations", name: "courses_organization_id_fk"
    add_foreign_key "exercise_owners", "exercises", name: "exercise_owners_exercise_id_fk"
    add_foreign_key "exercise_owners", "users", name: "exercise_owners_owner_id_fk", column: "owner_id"
    add_foreign_key "exercise_versions", "users", name: "exercise_versions_creator_id_fk", column: "creator_id"
    add_foreign_key "exercise_versions", "exercises", name: "exercise_versions_exercise_id_fk"
    add_foreign_key "exercise_versions", "irt_data", name: "exercise_versions_irt_data_id_fk", column: "irt_data_id"
    add_foreign_key "exercise_versions_resource_files", "exercise_versions", name: "exercise_versions_resource_files_exercise_version_id_fk"
    add_foreign_key "exercise_versions_resource_files", "resource_files", name: "exercise_versions_resource_files_resource_file_id_fk"
    add_foreign_key "exercise_versions", "stems", name: "exercise_versions_stem_id_fk"
    add_foreign_key "exercise_workouts", "exercises", name: "exercise_workouts_exercise_id_fk"
    add_foreign_key "exercise_workouts", "workouts", name: "exercise_workouts_workout_id_fk"
    add_foreign_key "exercises", "exercise_versions", name: "exercises_current_version_id_fk", column: "current_version_id"
    add_foreign_key "exercises", "exercise_families", name: "exercises_exercise_family_id_fk"
    add_foreign_key "exercises", "irt_data", name: "exercises_irt_data_id_fk", column: "irt_data_id"
    add_foreign_key "identities", "users", name: "identities_user_id_fk"
    add_foreign_key "prompt_answers", "attempts", name: "prompt_answers_attempt_id_fk"
    add_foreign_key "prompt_answers", "prompts", name: "prompt_answers_prompt_id_fk"
    add_foreign_key "prompts", "exercise_versions", name: "prompts_exercise_version_id_fk"
    add_foreign_key "prompts", "irt_data", name: "prompts_irt_data_id_fk", column: "irt_data_id"
    add_foreign_key "resource_files", "users", name: "resource_files_user_id_fk"
    add_foreign_key "student_extensions", "users", name: "student_extensions_user_id_fk"
    add_foreign_key "student_extensions", "workout_offerings", name: "student_extensions_workout_offering_id_fk"
    add_foreign_key "tag_user_scores", "users", name: "tag_user_scores_user_id_fk"
    add_foreign_key "test_case_results", "coding_prompt_answers", name: "test_case_results_coding_prompt_answer_id_fk"
    add_foreign_key "test_case_results", "test_cases", name: "test_case_results_test_case_id_fk"
    add_foreign_key "test_case_results", "users", name: "test_case_results_user_id_fk"
    add_foreign_key "test_cases", "coding_prompts", name: "test_cases_coding_prompt_id_fk"
    add_foreign_key "users", "workout_scores", name: "users_current_workout_score_id_fk", column: "current_workout_score_id"
    add_foreign_key "users", "global_roles", name: "users_global_role_id_fk"
    add_foreign_key "users", "time_zones", name: "users_time_zone_id_fk"
    add_foreign_key "workout_offerings", "workout_offerings", name: "workout_offerings_continue_from_workout_id_fk", column: "continue_from_workout_id"
    add_foreign_key "workout_offerings", "course_offerings", name: "workout_offerings_course_offering_id_fk"
    add_foreign_key "workout_offerings", "workouts", name: "workout_offerings_workout_id_fk"
    add_foreign_key "workout_offerings", "workout_policies", name: "workout_offerings_workout_policy_id_fk"
    add_foreign_key "workout_owners", "users", name: "workout_owners_owner_id_fk", column: "owner_id"
    add_foreign_key "workout_owners", "workouts", name: "workout_owners_workout_id_fk"
    add_foreign_key "workout_scores", "users", name: "workout_scores_user_id_fk"
    add_foreign_key "workout_scores", "workouts", name: "workout_scores_workout_id_fk"
    add_foreign_key "workout_scores", "workout_offerings", name: "workout_scores_workout_offering_id_fk"
    add_foreign_key "workouts", "users", name: "workouts_creator_id_fk", column: "creator_id"
  end
end