require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CourseOfferingsController do

  # This should return the minimal set of attributes required to create a valid
  # CourseOffering. As you add validations to CourseOffering, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "course_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CourseOfferingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all course_offerings as @course_offerings" do
      course_offering = CourseOffering.create! valid_attributes
      get :index, {}, valid_session
      assigns(:course_offerings).should eq([course_offering])
    end
  end

  describe "GET show" do
    it "assigns the requested course_offering as @course_offering" do
      course_offering = CourseOffering.create! valid_attributes
      get :show, {:id => course_offering.to_param}, valid_session
      assigns(:course_offering).should eq(course_offering)
    end
  end

  describe "GET new" do
    it "assigns a new course_offering as @course_offering" do
      get :new, {}, valid_session
      assigns(:course_offering).should be_a_new(CourseOffering)
    end
  end

  describe "GET edit" do
    it "assigns the requested course_offering as @course_offering" do
      course_offering = CourseOffering.create! valid_attributes
      get :edit, {:id => course_offering.to_param}, valid_session
      assigns(:course_offering).should eq(course_offering)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CourseOffering" do
        expect {
          post :create, {:course_offering => valid_attributes}, valid_session
        }.to change(CourseOffering, :count).by(1)
      end

      it "assigns a newly created course_offering as @course_offering" do
        post :create, {:course_offering => valid_attributes}, valid_session
        assigns(:course_offering).should be_a(CourseOffering)
        assigns(:course_offering).should be_persisted
      end

      it "redirects to the created course_offering" do
        post :create, {:course_offering => valid_attributes}, valid_session
        response.should redirect_to(CourseOffering.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved course_offering as @course_offering" do
        # Trigger the behavior that occurs when invalid params are submitted
        CourseOffering.any_instance.stub(:save).and_return(false)
        post :create, {:course_offering => { "course_id" => "invalid value" }}, valid_session
        assigns(:course_offering).should be_a_new(CourseOffering)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CourseOffering.any_instance.stub(:save).and_return(false)
        post :create, {:course_offering => { "course_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested course_offering" do
        course_offering = CourseOffering.create! valid_attributes
        # Assuming there are no other course_offerings in the database, this
        # specifies that the CourseOffering created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CourseOffering.any_instance.should_receive(:update).with({ "course_id" => "1" })
        put :update, {:id => course_offering.to_param, :course_offering => { "course_id" => "1" }}, valid_session
      end

      it "assigns the requested course_offering as @course_offering" do
        course_offering = CourseOffering.create! valid_attributes
        put :update, {:id => course_offering.to_param, :course_offering => valid_attributes}, valid_session
        assigns(:course_offering).should eq(course_offering)
      end

      it "redirects to the course_offering" do
        course_offering = CourseOffering.create! valid_attributes
        put :update, {:id => course_offering.to_param, :course_offering => valid_attributes}, valid_session
        response.should redirect_to(course_offering)
      end
    end

    describe "with invalid params" do
      it "assigns the course_offering as @course_offering" do
        course_offering = CourseOffering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CourseOffering.any_instance.stub(:save).and_return(false)
        put :update, {:id => course_offering.to_param, :course_offering => { "course_id" => "invalid value" }}, valid_session
        assigns(:course_offering).should eq(course_offering)
      end

      it "re-renders the 'edit' template" do
        course_offering = CourseOffering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CourseOffering.any_instance.stub(:save).and_return(false)
        put :update, {:id => course_offering.to_param, :course_offering => { "course_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested course_offering" do
      course_offering = CourseOffering.create! valid_attributes
      expect {
        delete :destroy, {:id => course_offering.to_param}, valid_session
      }.to change(CourseOffering, :count).by(-1)
    end

    it "redirects to the course_offerings list" do
      course_offering = CourseOffering.create! valid_attributes
      delete :destroy, {:id => course_offering.to_param}, valid_session
      response.should redirect_to(course_offerings_url)
    end
  end

end
