require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GlobalRolesController do

  # This should return the minimal set of attributes required to create a valid
  # GlobalRole. As you add validations to GlobalRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GlobalRolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all global_roles as @global_roles" do
      global_role = GlobalRole.create! valid_attributes
      get :index, {}, valid_session
      assigns(:global_roles).should eq([global_role])
    end
  end

  describe "GET show" do
    it "assigns the requested global_role as @global_role" do
      global_role = GlobalRole.create! valid_attributes
      get :show, {:id => global_role.to_param}, valid_session
      assigns(:global_role).should eq(global_role)
    end
  end

  describe "GET new" do
    it "assigns a new global_role as @global_role" do
      get :new, {}, valid_session
      assigns(:global_role).should be_a_new(GlobalRole)
    end
  end

  describe "GET edit" do
    it "assigns the requested global_role as @global_role" do
      global_role = GlobalRole.create! valid_attributes
      get :edit, {:id => global_role.to_param}, valid_session
      assigns(:global_role).should eq(global_role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GlobalRole" do
        expect {
          post :create, {:global_role => valid_attributes}, valid_session
        }.to change(GlobalRole, :count).by(1)
      end

      it "assigns a newly created global_role as @global_role" do
        post :create, {:global_role => valid_attributes}, valid_session
        assigns(:global_role).should be_a(GlobalRole)
        assigns(:global_role).should be_persisted
      end

      it "redirects to the created global_role" do
        post :create, {:global_role => valid_attributes}, valid_session
        response.should redirect_to(GlobalRole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved global_role as @global_role" do
        # Trigger the behavior that occurs when invalid params are submitted
        GlobalRole.any_instance.stub(:save).and_return(false)
        post :create, {:global_role => { "name" => "invalid value" }}, valid_session
        assigns(:global_role).should be_a_new(GlobalRole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GlobalRole.any_instance.stub(:save).and_return(false)
        post :create, {:global_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested global_role" do
        global_role = GlobalRole.create! valid_attributes
        # Assuming there are no other global_roles in the database, this
        # specifies that the GlobalRole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GlobalRole.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => global_role.to_param, :global_role => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested global_role as @global_role" do
        global_role = GlobalRole.create! valid_attributes
        put :update, {:id => global_role.to_param, :global_role => valid_attributes}, valid_session
        assigns(:global_role).should eq(global_role)
      end

      it "redirects to the global_role" do
        global_role = GlobalRole.create! valid_attributes
        put :update, {:id => global_role.to_param, :global_role => valid_attributes}, valid_session
        response.should redirect_to(global_role)
      end
    end

    describe "with invalid params" do
      it "assigns the global_role as @global_role" do
        global_role = GlobalRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GlobalRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => global_role.to_param, :global_role => { "name" => "invalid value" }}, valid_session
        assigns(:global_role).should eq(global_role)
      end

      it "re-renders the 'edit' template" do
        global_role = GlobalRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GlobalRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => global_role.to_param, :global_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested global_role" do
      global_role = GlobalRole.create! valid_attributes
      expect {
        delete :destroy, {:id => global_role.to_param}, valid_session
      }.to change(GlobalRole, :count).by(-1)
    end

    it "redirects to the global_roles list" do
      global_role = GlobalRole.create! valid_attributes
      delete :destroy, {:id => global_role.to_param}, valid_session
      response.should redirect_to(global_roles_url)
    end
  end

end
