require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResourceFilesController do

  # This should return the minimal set of attributes required to create a valid
  # ResourceFile. As you add validations to ResourceFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResourceFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all resource_files as @resource_files" do
      resource_file = ResourceFile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:resource_files).should eq([resource_file])
    end
  end

  describe "GET show" do
    it "assigns the requested resource_file as @resource_file" do
      resource_file = ResourceFile.create! valid_attributes
      get :show, {:id => resource_file.to_param}, valid_session
      assigns(:resource_file).should eq(resource_file)
    end
  end

  describe "GET new" do
    it "assigns a new resource_file as @resource_file" do
      get :new, {}, valid_session
      assigns(:resource_file).should be_a_new(ResourceFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested resource_file as @resource_file" do
      resource_file = ResourceFile.create! valid_attributes
      get :edit, {:id => resource_file.to_param}, valid_session
      assigns(:resource_file).should eq(resource_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ResourceFile" do
        expect {
          post :create, {:resource_file => valid_attributes}, valid_session
        }.to change(ResourceFile, :count).by(1)
      end

      it "assigns a newly created resource_file as @resource_file" do
        post :create, {:resource_file => valid_attributes}, valid_session
        assigns(:resource_file).should be_a(ResourceFile)
        assigns(:resource_file).should be_persisted
      end

      it "redirects to the created resource_file" do
        post :create, {:resource_file => valid_attributes}, valid_session
        response.should redirect_to(ResourceFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved resource_file as @resource_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceFile.any_instance.stub(:save).and_return(false)
        post :create, {:resource_file => {  }}, valid_session
        assigns(:resource_file).should be_a_new(ResourceFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceFile.any_instance.stub(:save).and_return(false)
        post :create, {:resource_file => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested resource_file" do
        resource_file = ResourceFile.create! valid_attributes
        # Assuming there are no other resource_files in the database, this
        # specifies that the ResourceFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ResourceFile.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => resource_file.to_param, :resource_file => { "these" => "params" }}, valid_session
      end

      it "assigns the requested resource_file as @resource_file" do
        resource_file = ResourceFile.create! valid_attributes
        put :update, {:id => resource_file.to_param, :resource_file => valid_attributes}, valid_session
        assigns(:resource_file).should eq(resource_file)
      end

      it "redirects to the resource_file" do
        resource_file = ResourceFile.create! valid_attributes
        put :update, {:id => resource_file.to_param, :resource_file => valid_attributes}, valid_session
        response.should redirect_to(resource_file)
      end
    end

    describe "with invalid params" do
      it "assigns the resource_file as @resource_file" do
        resource_file = ResourceFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => resource_file.to_param, :resource_file => {  }}, valid_session
        assigns(:resource_file).should eq(resource_file)
      end

      it "re-renders the 'edit' template" do
        resource_file = ResourceFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResourceFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => resource_file.to_param, :resource_file => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested resource_file" do
      resource_file = ResourceFile.create! valid_attributes
      expect {
        delete :destroy, {:id => resource_file.to_param}, valid_session
      }.to change(ResourceFile, :count).by(-1)
    end

    it "redirects to the resource_files list" do
      resource_file = ResourceFile.create! valid_attributes
      delete :destroy, {:id => resource_file.to_param}, valid_session
      response.should redirect_to(resource_files_url)
    end
  end

end
